# ?????
server:
  port: 7090
  servlet:
    session:
      timeout: PT60M
    context-path: /api
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html
#  api-docs:
#    path: /v3/api-docs
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
      gargoylesoftware: off
    root: debug
  config: classpath:logback-spring.xml
  file:
    path: logs
spring:
  application:
    name: haustoj
  mvc:
    favicon:
      enable: false
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://49.232.180.87:3306/haustoj?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: ouyu1
    password: 13937354505yZy*
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    port: 465
    username: test@qq.com
    password: 123456
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
  config:
    import:
      - nacos:${nacos-switch-config}.${spring.cloud.nacos.config.file-extension}
      - nacos:${nacos-web-config}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        file-extension: yml #指定yaml格式的配置
        group: DEFAULT_GROUP  # 指定分组
        namespace: ec08f649-1d5c-4084-b761-da49e6e521ff
        type: yaml
        prefix: haustoj
      url: http://localhost:8848
nacos-switch-config: haustoj-switch
nacos-web-config: haustoj-web

haustoj:
  jwt:
    secret: haustoj
    expire: 86400
    check-refresh-expire: 3600
    header: Authorization
